version: '3.8'
services:
  # django
  django:
    container_name: django
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - 80:8000
    env_file:
      - ./.env
    build:
      context: .
      dockerfile: ./.docker/Dockerfile
    restart: always
    working_dir: /usr/src/app
    volumes:
      - ./:/usr/src/app
    networks:
      - myNetwork

  #MySQL Service
  db:
    image: mysql:5.7
    container_name: db
    restart: always
    tty: true
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: django
      MYSQL_USER: django
      MYSQL_PASSWORD: django
      MYSQL_ROOT_PASSWORD: django
    volumes:
      - mysqldata:/var/lib/mysql/
    networks:
      - myNetwork

  # phpmyadmin
  phpmyadmin:
    image: 'phpmyadmin'
    container_name: phpmyadmin
    environment:
        PMA_HOST: mysql
        PMA_PASSWORD: django
        PMA_ARBITRARY: 1
    restart: always
    ports:
        - 8080:80
    networks:
        - myNetwork

  redis:
    image: redis:6.2-alpine
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
    volumes: 
      - redis:/redis
    networks:
      - myNetwork
  
  celery-worker:
    build:
      context: .
      dockerfile: ./.docker/Dockerfile
    container_name: celery-worker
    working_dir: /usr/src/app
    command: celery -A src worker -l info
    env_file:
      - ./.env
    volumes:
      - ./:/usr/src/app
    depends_on:
      - django
      - redis
      - db
    restart: always
    networks:
      - myNetwork

  celery-beat:
    build:
      context: .
      dockerfile: ./.docker/Dockerfile
    container_name: celery-beat
    working_dir: /usr/src/app
    env_file:
      - ./.env
    command: celery -A src beat -l info
    volumes:
      - ./:/usr/src/app
    depends_on:
      - django
      - redis
      - db
    restart: always
    networks:
      - myNetwork

#Docker Networks
networks:
  myNetwork:
    driver: bridge
volumes:
  mysqldata:
  redis: