# Generated by Django 4.1 on 2022-08-31 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0003_alter_ticket_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='_from',
            new_name='time_from',
        ),
    ]
