# Generated by Django 4.1 on 2022-09-01 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0005_userclient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userclient',
            name='password',
            field=models.BinaryField(null=True),
        ),
    ]
