# Generated by Django 4.1 on 2022-09-01 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0006_alter_userclient_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userclient',
            name='password',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
